
---
# Default values for eck-stack.
# This is a YAML-formatted file.

# If enabled, will use the eck-elasticsearch chart and deploy an Elasticsearch resource.
#
eck-elasticsearch:
  enabled: true

  fullnameOverride: eck-elasticsearch

  ingress:
    enabled: true
    
    annotations:
      kubernetes.io/ingress.class: nginx

    pathType: Prefix
    hosts:
      - host: elasticsearch.local
        paths:
          - /
    tls:
      enabled: false

# If enabled, will use the eck-kibana chart and deploy a Kibana resource.
#
eck-kibana:
  enabled: true

  elasticsearchRef:
    name: eck-elasticsearch

  ingress:
    enabled: true
    
    annotations:
      kubernetes.io/ingress.class: nginx

    pathType: Prefix
    hosts:
      - host: kibana.local
        paths:
          - /
    tls:
      enabled: false

# If enabled, will use the eck-agent chart and deploy an Elastic Agent instance.
#
eck-agent:
  enabled: true

  elasticsearchRef:
    name: eck-elasticsearch
    namespace: elk-stack

  deployment:
    podTemplate:
      spec:
        containers:
        - name: agent
          securityContext:
            runAsUser: 0


  config:
    inputs:
      # Collect logs from Kubernetes system components
      - name: kubernetes-logs
        type: log
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              in_cluster: true

      # Collect logs from Prometheus
      - name: prometheus-logs
        type: log
        paths:
          - /var/log/prometheus/*.log

      # Collect logs from Ingress-NGINX
      - name: ingress-nginx-logs
        type: log
        paths:
          - /var/log/containers/*ingress-nginx*.log

      # Collect logs from Kubernetes Dashboard
      - name: kubernetes-dashboard-logs
        type: log
        paths:
          - /var/log/containers/*kubernetes-dashboard*.log

      # Collect metrics from Prometheus
      - name: prometheus-metrics
        type: prometheus/metrics
        enabled: true
        hosts:
          - http://prometheus.monitoring.svc.cluster.local:9090/metrics

      # Collect metrics from Kubernetes API server
      - name: kubernetes-metrics
        type: kubernetes/metrics
        enabled: true
