---
apiVersion: v1
kind: Namespace
metadata:
  name:  monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ImDimchkee/k8s-prom-argo-ingress.git'
    targetRevision: HEAD
    path: charts/kube-prometheus-stack
    helm:
      valueFiles:
        - ../../values/kube-prometheus-stack/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
