---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-app
  namespace: ingress-nginx
spec:
  project: default
  source:
    repoURL: 'https://github.com/ImDimchkee/k8s-prom-argo-ingress.git'
    targetRevision: HEAD
    path: charts/ingress-nginx
    helm:
      valueFiles:
        - ../../values/ingress-nginx/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
