---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  project: default
  source:
    repoURL: 'https://github.com/ImDimchkee/k8s-prom-argo-ingress.git'
    targetRevision: HEAD
    path: charts/nginx-ingress
    helm:
      valueFiles:
        - ../../values/nginx-ingress/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
